### ISSUE TITLE
OAuth login isn't implemented correctly

### ISSUE THREAD

**Issue by lambadalambda** [ReticentJohn/Amaroq#49] opened 2017-09-14 09:53 UTC
Amaroq uses a weird login scheme to get the access_token, logging in on a webview and then waiting for an access code to appear in the html. This isn't a valid oauth flow and will possibly break in the future if Mastodon changes it's html. Amaroq should probably implement the usual oauth token exchange mechanism.

I found the issue because Pleroma also implements the Mastodon API, but has different html, so it breaks there.

**Comment by ReticentJohn** [comment] 2017-09-14 12:11
This is an unfortunate reality until the API provides access to the ability to alter account preferences. While admittedly strange, running this login method allows the app’s shared urlsession to retain cookies and continue to have access to parts of a Mastodon instance that would otherwise be unreachable by the API alone.

Perhaps to mitigate risk, the login should be upgraded to use the standard flow, and when accessing account preferences the user would just have to login again.

I’ll accept PR’s from anyone who wants to change Amaroq’s login process but I probably won’t do it myself until if/when it actually breaks on mastodon.social.

**Comment by lambadalambda** [comment] 2017-09-14 16:58
Interesting! Thanks for the explanation!

**Comment by zspencer** [comment] 2017-10-15 23:08
Not sure if this is the cause or not, but I've found that I cannot log in to mastodon.social? 

It spins forever: https://zspencer.keybase.pub/IMG_3300.TRIM.mov

Not sure if there is a debug log bundle I can send to ya?

**Comment by ReticentJohn** [comment] 2017-10-15 23:32
This is indeed the issue that has surfaced in v2 of Mastodon. The app will need to be reworked to use the proper oauth flow documented in Mastodon’s API and as a result, the Edit Profile and Account Preferences areas of the app will also need to boot the user off to Safari, instead of handling it in the app. (There is API available for edit profile now but that would require UI work on top of everything)

I will be getting to this as soon as I am able, but cannot say this’ll be fixed quickly. :(

**Comment by moritzheiber** [comment] 2017-10-19 07:29
FYI, this is fixed in the latest TestFlight beta.

**Closed** 2017-10-19 23:58 UTC

**Comment by Fatima-yo** [comment] 2021-06-10 15:45
Hello people, I am getting this same error using Amaroq on iPhone
Any hints will be highly appreciated
