### ISSUE TITLE
UIControlEvent action for follow icon seems to be failing

### ISSUE THREAD

**Issue by dddjjjbbb** [ReticentJohn/Amaroq#124] opened 2019-12-04 23:31 UTC
__Version__: v1.1.16 (652)
__OS__: 13.1.3
__Device__: iPhone 6s

__Steps to reproduce__:

* Tap search icon
* Enter an account
* Tap "search" in keyboard
* Tap an account
* On redirect, tap the follow icon

__Expected result(s)__:

* Icon is highlighted
* Account is followed
* Account is shown in "FOLLOWS" list in profile

__Actual result__:

* Icon is highlighted
* Account is **not** followed
* Account is __not__ shown in "FOLLOWS" list in profile

**Comment by Casuallynoted** [comment] 2019-12-19 04:02
I am experiencing this bug as well. I have to use an alternate Mastodon app if I want to follow users.

**Comment by kflak** [comment] 2020-02-20 14:22
Same thing here. iPhone SE, iOS 13.3.1. Pushing Follow makes the icon light up for a moment, then go back to gray. No following follows.

**Comment by ReticentJohn** [comment] 2020-06-02 01:08
Duplicate of #122 this'll be fixed in 1.1.17

**Closed by ReticentJohn** 2020-06-02 01:08 UTC
