### ISSUE TITLE
Keep scroll-position on timeline refresh

### ISSUE THREAD

**Issue by JanJastrow** [ReticentJohn/Amaroq#59] opened 2017-11-03 14:35 UTC
Hi there,

thank you for Amaroq, pretty smooth and fast Mastodon client.
Could you implement a feature, that would keep the timeline in place (centered on a toot), when new toots come in?
(Similar to Tweetbot)

BR
Jan

**Comment by Floppy** [comment] 2017-11-20 09:16
I would also love this feature. I suspect that it really needs support in Mastodon itself to store the scroll position, because you certainly want this working consistently across both Amaroq and the web client.

**Comment by ReticentJohn** [comment] 2017-11-20 21:21
I'm really unsure how scroll position could feasibly be an API feature, since everyone's clients are different - it's just heavily reliant on being able to locate the position of the currently viewed toot. That said, I have something of a solution on the TestFlight beta now, but I'm not fully satisfied with it. It still doesn't work with fast-moving feeds because the currently visible toot sinks below the first page on the refreshed timeline. There's a few alternatives that I could take (listening to the streaming API or pulling multiple pages of toots at once) but I'm short on time. :( This will continue to be an objective for me.

**Comment by Floppy** [comment] 2017-11-21 10:05
http://tweetmarker.net/ was a cross-platform solution for Twitter (I think before Twitter did it itself) - perhaps the way they do it might be useful to compare.

**Comment by apiarian** [comment] 2017-11-22 16:35
looks like this is a duplicate of #3 , though with the added request to synchronize between clients, which may be rather a feature request for the mastodon project itself?

**Comment by ReticentJohn** [comment] 2017-11-22 16:44
Yeah, we could be combating this from two angles. My intention was always to figure out how to do this from the Amaroq client specifically, but if Mastodon extends this feature it would change things dramatically.

**Closed** 2021-07-13 13:54 UTC
