### ISSUE TITLE
double notifications on iOS 10

### ISSUE THREAD

**Issue by nightpool** [ReticentJohn/Amaroq#60] opened 2017-11-11 21:41 UTC
I haven't updated to 11 yet (don't like the UI, *lots* of bugs) but that means I'm getting tons of duplicate notifications—every notif I get comes twice. is there an easy way to fix this? maybe turning off the "silent" notification type server-side?

**Comment by ReticentJohn** [comment] 2017-11-16 23:28
I am working on a more permanent fix for this situation through an update, but you should be able to completely stop the duplicate notifications by turning off background refreshing.

**Comment by nightpool** [comment] 2017-11-20 19:56
@ReticentJohn That fixed it for a few days, but unfortunately it started happening again recently (even with the setting still off)

**Comment by ReticentJohn** [comment] 2017-11-20 21:15
Crud, maybe something wrong with my notification server running across two dynos. I'll look further into this, thanks.

**Comment by nightpool** [comment] 2017-11-24 18:30
still seems to be happening on the most recent version of Amaroq, just FYI

**Comment by ReticentJohn** [comment] 2017-11-30 03:23
Still trying to figure this one out, I haven't been able to find anything wrong with the notification server, so I'm beginning to think there may be something wrong with how I'm registering on firebase? I'll continue on this saga...

**Comment by ReticentJohn** [comment] 2018-04-19 18:55
On returning and finally reproducing this issue first hand, I believe I was able to fix this server side. The notification server was not defending against duplicate registration requests well enough, due to a misunderstanding of sequelize's findOrCreate record documentation. Please let me know if you continue to see duplicates though.

**Closed by ReticentJohn** 2018-04-19 18:55 UTC
